# Generated by Django 4.1 on 2024-09-23 20:56

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import home.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_published', models.DateTimeField(auto_now_add=True)),
                ('updated', models.BooleanField(default=True)),
                ('num_rows', models.PositiveIntegerField(blank=True, null=True)),
                ('num_columns', models.PositiveIntegerField(blank=True, null=True)),
                ('df_file', models.FilePathField(path='C:\\Users\\am_ke\\source\\repos\\kingofbrooklyn\\predictstat\\media')),
                ('title', models.CharField(blank=True, max_length=50)),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DatasetUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_published', models.DateTimeField(auto_now_add=True)),
                ('updated', models.BooleanField(default=True)),
                ('title', models.CharField(blank=True, max_length=50)),
                ('df_file', models.FileField(upload_to=home.models.Dataset.user_directory_path)),
                ('dataset', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='home.dataset')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Histogram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_published', models.DateTimeField(auto_now_add=True)),
                ('updated', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=20)),
                ('fig_file', models.FileField(blank=True, upload_to=home.models.VisualizationXAbstract.user_directory_path)),
                ('nbins', models.PositiveIntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('x', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='home.dataset')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrdinaryLeastSquares',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_published', models.DateTimeField(auto_now_add=True)),
                ('updated', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=20)),
                ('reg_file', models.FileField(blank=True, null=True, upload_to=home.models.RegressionXYAbstract.user_directory_path)),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('x', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss_as_x', to='home.dataset')),
                ('y', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss_as_y', to='home.dataset')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PredictionOrdinaryLeastSquares',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_published', models.DateTimeField(auto_now_add=True)),
                ('updated', models.BooleanField(default=True)),
                ('title', models.CharField(blank=True, max_length=50)),
                ('y_file', models.FileField(blank=True, upload_to=home.models.Dataset.user_directory_path)),
                ('regression', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)ss', to='home.ordinaryleastsquares')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('x', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss_as_x', to='home.dataset')),
                ('y', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss_as_y', to='home.dataset')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PredictionRidgeRegression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_published', models.DateTimeField(auto_now_add=True)),
                ('updated', models.BooleanField(default=True)),
                ('title', models.CharField(blank=True, max_length=50)),
                ('y_file', models.FileField(blank=True, upload_to=home.models.Dataset.user_directory_path)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RidgeRegression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_published', models.DateTimeField(auto_now_add=True)),
                ('updated', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=20)),
                ('reg_file', models.FileField(blank=True, null=True, upload_to=home.models.RegressionXYAbstract.user_directory_path)),
                ('alpha', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('solver', models.CharField(blank=True, choices=[('auto', 'auto'), ('lbfgs', 'lbfgs'), ('cholesky', 'cholesky'), ('sparse_cg', 'sparse_cg')], default=None, max_length=9, null=True)),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('x', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss_as_x', to='home.dataset')),
                ('y', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss_as_y', to='home.dataset')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ScatterMatrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_published', models.DateTimeField(auto_now_add=True)),
                ('updated', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=20)),
                ('fig_file', models.FileField(blank=True, upload_to=home.models.VisualizationXAbstract.user_directory_path)),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('x', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='home.dataset')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_published', models.DateTimeField(auto_now_add=True)),
                ('updated', models.BooleanField(default=True)),
                ('title', models.CharField(default='Workspace', max_length=20)),
                ('datasets', models.ManyToManyField(related_name='%(class)ss', to='home.dataset')),
                ('datasetuploads', models.ManyToManyField(related_name='%(class)ss', to='home.datasetupload')),
                ('histograms', models.ManyToManyField(related_name='%(class)ss', to='home.histogram')),
                ('ordinaryleastsquaress', models.ManyToManyField(related_name='%(class)ss', to='home.ordinaryleastsquares')),
                ('predictionordinaryleastsquaress', models.ManyToManyField(related_name='%(class)ss', to='home.predictionordinaryleastsquares')),
                ('predictionridgeregressions', models.ManyToManyField(related_name='%(class)ss', to='home.predictionridgeregression')),
                ('ridgeregressions', models.ManyToManyField(related_name='%(class)ss', to='home.ridgeregression')),
                ('scattermatrixs', models.ManyToManyField(related_name='%(class)ss', to='home.scattermatrix')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='predictionridgeregression',
            name='regression',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)ss', to='home.ridgeregression'),
        ),
        migrations.AddField(
            model_name='predictionridgeregression',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='predictionridgeregression',
            name='x',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss_as_x', to='home.dataset'),
        ),
        migrations.AddField(
            model_name='predictionridgeregression',
            name='y',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss_as_y', to='home.dataset'),
        ),
    ]
