# Generated by Django 4.1 on 2024-09-25 03:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_time_published_dataset_time_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ridgeregression',
            name='alpha',
            field=models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='ridgeregression',
            name='solver',
            field=models.CharField(choices=[('auto', 'auto'), ('lbfgs', 'lbfgs'), ('cholesky', 'cholesky'), ('sparse_cg', 'sparse_cg')], default='auto', max_length=9),
        ),
    ]
